# Check Py files GitHub Action config file
name: CheckPythonFiles

on:
  workflow_call:
    outputs:
      py_files_changed:
        description: 'Check if py files have changed.'
        value: ${{ jobs.check_py_files.outputs.py_files_changed }}

jobs:
  check_py_files:
    runs-on: ubuntu-latest
    outputs:
      py_files_changed: ${{ steps.check.outputs.py_files_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Check for changed py files in classes or functions.
        id: check
        env:
          PREVIOUS_COMMIT: ${{ github.event.workflow_run.before }}
          CURRENT_COMMIT: ${{ github.event.workflow_run.sha }}
        run: |
          set -euxo pipefail
          echo "$PREVIOUS_COMMIT"
          echo "CURRENT_COMMIT"
          
          files=$(git diff --name-only $CURRENT_COMMIT $PREVIOUS_COMMIT | grep -E '^classes/.*\.py$|^functions/.*\.py$')
          echo "Changed files: $files"
          
          if [ -n "$files" ]; then
              echo "Python files have changed in classes or functions."
              echo "py_files_changed=true" >> $GITHUB_ENV
          else
              echo "No Python files have changed in classes or functions."
          fi;