name: CheckPythonFiles

on:
  workflow_call:

jobs:
  check_py_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Get changed Python files in classes folder
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            classes/**/*.py
      
      - name: Set output based on changes
        id: set-output
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "::set-output name=py_files_changed::true"
          else
            echo "::set-output name=py_files_changed::false"
          fi;
