name: conditional

on:
    push:

jobs:
    job_a:
        name: a
        runs-on: ubuntu-latest
        steps:
            - run: echo "A"
            - id: set
              run: |
                echo "{run_job_b}={no}" >> $GITHUB_OUTPUT
        outputs:
            run_job_b: ${{steps.set.outputs.run_job_b}}
    
    job_b:
        name: b
        runs-on: ubuntu-latest
        needs:
            - job_a
        if: needs.job_a.outputs.run_job_b == 'yes'
        steps:
            - run: echo "B"
    
    job_c:
        name: c
        runs-on: ubuntu-latest
        needs:
            - job_a
            - job_b
        if: |
            always() &&
            (needs.job_a.result == 'success' &&
            (needs.job_b.result == 'success' || needs.job_b.result == 'skipped')
            )
        steps:
            - run: echo "C"